"""empty message

Revision ID: 2e797074a63f
Revises: 992be3140395
Create Date: 2022-02-02 15:19:20.787796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e797074a63f'
down_revision = '992be3140395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('language', sa.String(length=7), nullable=False))
    op.add_column('clip', sa.Column('user', sa.String(length=20), nullable=False))
    op.add_column('sentence', sa.Column('user', sa.String(length=20), nullable=False))
    op.add_column('unrecognized', sa.Column('language', sa.String(length=7), nullable=False))
    op.add_column('unrecognized', sa.Column('user', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unrecognized', 'user')
    op.drop_column('unrecognized', 'language')
    op.drop_column('sentence', 'user')
    op.drop_column('clip', 'user')
    op.drop_column('clip', 'language')
    # ### end Alembic commands ###
