"""empty message

Revision ID: 7df683748fd7
Revises: d77babfffd5d
Create Date: 2022-02-12 11:48:48.084651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df683748fd7'
down_revision = 'd77babfffd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('dataset_type', sa.String(length=7), nullable=False))
    op.add_column('clip', sa.Column('dataset_version', sa.String(length=7), nullable=False))
    op.create_unique_constraint('_text_user_uc', 'sentence', ['text', 'user'])
    op.drop_index('text', table_name='sentence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('text', 'sentence', ['text'], unique=True)
    op.drop_constraint('_text_user_uc', 'sentence', type_='unique')
    op.drop_column('clip', 'dataset_version')
    op.drop_column('clip', 'dataset_type')
    # ### end Alembic commands ###
