"""empty message

Revision ID: 992be3140395
Revises: e70b9c25fda7
Create Date: 2022-01-23 18:14:10.789371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992be3140395'
down_revision = 'e70b9c25fda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unrecognized',
    sa.Column('id', sa.String(length=192), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clip', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clip', 'data')
    op.drop_table('unrecognized')
    # ### end Alembic commands ###
