"""empty message

Revision ID: e70b9c25fda7
Revises: 
Create Date: 2021-10-16 17:14:40.683138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70b9c25fda7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence',
    sa.Column('id', sa.String(length=192), nullable=False),
    sa.Column('language', sa.String(length=7), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('clip',
    sa.Column('id', sa.String(length=192), nullable=False),
    sa.Column('sentence_id', sa.String(length=192), nullable=True),
    sa.Column('positiveVotes', sa.Integer(), nullable=True),
    sa.Column('negativeVotes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clip')
    op.drop_table('sentence')
    # ### end Alembic commands ###
